Improve prepare command logs
containous/maesh pull request #717
Opened 2020-08-28 13:25 UTC by jspdown

## What does this PR do?

This PR reworks the log messages of the prepare command. So logs which are considered useful for debugging have been move to the DEBUG level. Some context has been added to the logs.

Fixes #660 

### How to test it

* run `maesh prepare` a local cluster, try with the `--logLevel` option

2020-08-28 15:17 UTC, kevinpollet requested changes

2020-08-28 15:17 UTC, kevinpollet commented on pkg/dns/dns.go
> +	return nil, fmt.Errorf("unable to get CoreDNS container in deployment %q in namespace %q", deployment.Namespace, deployment.Name)
```suggestion
	return nil, fmt.Errorf("unable to get CoreDNS container in deployment %q in namespace %q", deployment.Name, deployment.Namespace)
```

2020-08-28 15:18 UTC, jspdown commented on pkg/dns/dns.go
> +	return nil, fmt.Errorf("unable to get CoreDNS container in deployment %q in namespace %q", deployment.Namespace, deployment.Name)
:eagle: Good catch!

2020-08-31 07:45 UTC, kevinpollet approved these changes
LGTM 🚢

2020-08-31 07:46 UTC, merged